# Generated by Django 4.1.5 on 2023-02-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-id'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
